f = open('Codingal.txt',"r")
print("\nThe first line of the file")
print(f.readline())
f.close()
f = open('Codingal.txt',"r")
print("\nThe three lines of the file")
print(f.readline())
print(f.readline())
print(f.readline())
f.close()
f = open('Codingal.txt',"r")
print("\nlooping the lines")
for line in f:
    print(line)
f.close()