file = open("myflile.txt", "w")  
file.write("Hi my name is Divyesh. \nI am 10 years old. \nI am learing Python")
file.close()
file = open("myflile.txt", "r")
print(file.read())
file.close()
file = open("myfile.txt", "a")
file.write("\nI live in Nepal.")
file.close()
file = open("myfile.txt", "r")
print(file.read())