file = open("Tiger.txt","w")
file.write("The tiger is the largest species among the Felidae and classified in the genus Panthera.")
file.close()
file = open("Tiger.txt","r")
print(file.read())
file.close()
file = open("Tiger.txt","a")
file.write("\nTigers are apex predators, primarily preying on ungulates such as deer and wild boar.")
file.close()
file = open("Tiger.txt","r")
print(file.read())
file.close()